spring.application.name=dollar
server.port=8080

### Spring JPA ###
#Show the SQL in the console
spring.jpa.show-sql=false
#Show the bind parameters (The values for the '?' in the query)
logging.level.org.hibernate.orm.jdbc.bind=OFF
#Make the SQL look pretty (formatted) instead of one long line
spring.jpa.properties.hibernate.format_sql=true

### Logging ###
logging.level.root=INFO
logging.level.com.paradoxdevs.dollar=DEBUG
#logging.file.name=logs/dollar-app.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.total-size-cap=100MB
logging.level.org.springframework.web.filter=DEBUG
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR