spring.application.name=dollar

### H2 Config ####
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:test_db;DATABASE_TO_UPPER=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

### Spring JPA ###
spring.jpa.defer-datasource-initialization=true
#Show the SQL in the console
spring.jpa.show-sql=true
#SHOW THE BIND PARAMETERS (The values for the '?' in the query)
logging.level.org.hibernate.orm.jdbc.bind=TRACE
#Make the SQL look pretty (formatted) instead of one long line
spring.jpa.properties.hibernate.format_sql=true

### Logging ###
logging.level.root=INFO
logging.level.com.paradoxdevs.dollar=DEBUG
#logging.file.name=logs/dollar-app.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.total-size-cap=100MB