create table public.transactions (
    id bigint generated by default as identity primary key,
    name text not null,
    description text,
    transaction_type text not null,
    amount float4 not null,
    currency text not null,
    created_at timestamptz default now()
);