ALTER TABLE transactions
ADD COLUMN IF NOT EXISTS created_by UUID REFERENCES users(uuid),
ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
ADD COLUMN IF NOT EXISTS updated_by UUID REFERENCES users(uuid),
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT now() NOT NULL;
